# koala_diff/reporter.py

import json
from jinja2 import Environment, FileSystemLoader, select_autoescape
import os

class HtmlReporter:
    """
    Generates HTML reports from diff results.
    """
    def __init__(self, output_path: str = "diff_report.html"):
        self.output_path = output_path

    def generate(self, diff_result: dict, title: str = "Koala Diff Report"):
        """
        Renders the diff result into an HTML file.
        """
        env = Environment(
            loader=FileSystemLoader(os.path.dirname(__file__)),
            autoescape=select_autoescape(['html', 'xml'])
        )
        
        # Simple template string for MVP (later move to separate .html file)
        template_str = """
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>{{ title }}</title>
            <style>
                body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; background-color: #f8f9fa; color: #343a40; padding: 2rem; }
                .container { max-width: 960px; margin: 0 auto; }
                .card { background: white; border-radius: 8px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); padding: 2rem; margin-bottom: 1.5rem; }
                h1 { color: #2c3e50; margin-bottom: 0.5rem; }
                .stat-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 1rem; margin-top: 1rem; }
                .stat-box { background: #f1f3f5; padding: 1.5rem; border-radius: 6px; text-align: center; }
                .stat-value { font-size: 2rem; font-weight: 700; color: #228be6; }
                .stat-label { font-size: 0.875rem; text-transform: uppercase; letter-spacing: 0.5px; color: #868e96; margin-top: 0.5rem; }
                .badge-added { color: #40c057; }
                .badge-removed { color: #fa5252; }
                table { width: 100%; border-collapse: collapse; margin-top: 1rem; }
                th, td { text-align: left; padding: 0.75rem; border-bottom: 1px solid #dee2e6; }
                th { background-color: #f8f9fa; }
                .alert-row { background-color: #ffe8cc; color: #d9480f; }
            </style>
        </head>
        <body>
            <div class="container">
                <div class="card">
                    <h1>🐨 {{ title }}</h1>
                    <p>Comparison Summary generated by Koala Diff</p>
                </div>
                
                <div class="card">
                    <h2>Overview</h2>
                    <div class="stat-grid">
                        <div class="stat-box">
                            <div class="stat-value">{{ total_rows_a }}</div>
                            <div class="stat-label">Rows in File A</div>
                        </div>
                        <div class="stat-box">
                            <div class="stat-value">{{ total_rows_b }}</div>
                            <div class="stat-label">Rows in File B</div>
                        </div>
                        <div class="stat-box">
                            <div class="stat-value">{{ matched }}</div>
                            <div class="stat-label">Identical Rows</div>
                        </div>
                    </div>
                    
                    <div class="stat-grid">
                         <div class="stat-box">
                            <div class="stat-value badge-added">+{{ added }}</div>
                            <div class="stat-label">New Rows</div>
                        </div>
                        <div class="stat-box">
                            <div class="stat-value badge-removed">-{{ removed }}</div>
                            <div class="stat-label">Removed Rows</div>
                        </div>
                    </div>
                </div>

                <div class="card">
                    <h2>Column Statistics</h2>
                    <table>
                        <thead>
                            <tr>
                                <th>Column</th>
                                <th>Nulls (A)</th>
                                <th>Nulls (B)</th>
                                <th>Change</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for col, counts in null_counts.items() %}
                            <tr {% if counts[0] != counts[1] %}class="alert-row"{% endif %}>
                                <td>{{ col }}</td>
                                <td>{{ counts[0] }}</td>
                                <td>{{ counts[1] }}</td>
                                <td>{{ counts[1] - counts[0] }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>

                <div class="card">
                    <h2>Modified Columns</h2>
                    {% if modified_cols %}
                    <p>The following columns had value changes in matching rows:</p>
                    <ul>
                        {% for col in modified_cols %}
                        <li><code>{{ col }}</code></li>
                        {% endfor %}
                    </ul>
                    {% else %}
                    <p>No column modifications detected in matched rows.</p>
                    {% endif %}
                </div>
            </div>
        </body>
        </html>
        """
        
        from jinja2 import Template
        template = Template(template_str)
        
        html_out = template.render(title=title, **diff_result)
        
        with open(self.output_path, "w") as f:
            f.write(html_out)
        
        print(f"✅ HTML Report saved to: {self.output_path}")
